# Generated by Django 4.0.3 on 2022-05-15 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('description', models.TextField(max_length=5000)),
                ('category', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('published_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
