# Generated by Django 4.0.3 on 2022-05-16 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_product_image_product_subcategory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AddField(
            model_name='product',
            name='imageback',
            field=models.ImageField(default=0, upload_to='product/'),
        ),
        migrations.AddField(
            model_name='product',
            name='imagefront',
            field=models.ImageField(default=0, upload_to='product/'),
        ),
        migrations.AddField(
            model_name='product',
            name='imageother1',
            field=models.ImageField(default=0, upload_to='product/'),
        ),
        migrations.AddField(
            model_name='product',
            name='imageother2',
            field=models.ImageField(default=0, upload_to='product/'),
        ),
    ]
