# Generated by Django 4.0.3 on 2022-05-16 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_product_subcategory_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='label',
            field=models.CharField(choices=[('null', 'Null'), ('new', 'New'), ('30% Off', '30% Off'), ('top', 'Top')], default='null', max_length=8),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('clothing', 'Clothing'), ('shoes', 'Shoes'), ('bag', 'Bag'), ('trouser', 'Trouser'), ('jacket', 'Jacket')], default='clothing', max_length=8),
        ),
        migrations.AlterField(
            model_name='product',
            name='subcategory',
            field=models.CharField(choices=[('women', 'Women'), ('men', 'Men')], default='women', max_length=6),
        ),
    ]
