# Generated by Django 4.0.4 on 2022-05-30 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_shippingaddress_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='desription',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='email',
            field=models.EmailField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='products',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.product'),
        ),
        migrations.RemoveField(
            model_name='review',
            name='name',
        ),
        migrations.AddField(
            model_name='review',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
