# Generated by Django 4.0.4 on 2022-05-30 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_review_desription_review_email_review_products_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('foundation', 'Foundation'), ('lips', 'Lips'), ('eyes', 'Eyes'), ('face', 'Face'), ('blenders', 'Blenders'), ('hair spray', 'Hair Spray'), ('brushes', 'Brushes')], default='foundation', max_length=20),
        ),
    ]
