# Generated by Django 4.0.4 on 2022-05-30 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_product_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='subcategory',
            field=models.CharField(choices=[('waterproof foundation', 'WaterProof Foundation'), ('glossy lipsticks', 'Glossy Lipsticks')], default='glossy lipsticks', max_length=50),
        ),
    ]
