# Generated by Django 4.0.4 on 2022-06-25 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_alter_product_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('shirts', 'shirts'), ('trousers', 'trousers'), ('shoes', 'shoes'), ('bags', 'bags'), ('pent', 'pent'), ('short', 'short')], default='shirts', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='subcategory',
            field=models.CharField(choices=[('men', 'men'), ('women', 'women')], default='men', max_length=50),
        ),
    ]
